/**
 * /oauth/authorize  (GET, POST) and /oauth/authorize/finalize  (GET).
 *
 * Flow:
 *   1. /oauth/authorize → Authlete /auth/authorization → store ctx via
 *      ticket/update → 302 to auth-ui with the ticket.
 *   2. auth-ui completes login + consent and records the decision via
 *      POST /api/interactions/{ticket} (see interactions.ts).
 *   3. auth-ui 302s the browser back to /oauth/authorize/finalize?ticket=...
 *      which reads the decision, calls Authlete /auth/authorization/issue
 *      (or /fail), and 302s the RP's redirect URL directly.
 *
 * The authorization code is generated by Authlete on /issue and emitted by
 * the AS in the final 302 — it never passes through auth-ui.
 */

import type { Context } from "hono";
import { Hono } from "hono";
import { authlete } from "../authlete.js";
import { config } from "../config.js";
import { loadContext, storeContext } from "../context.js";
import { jsonHeaders } from "../http.js";

export const authorize = new Hono();

async function handleAuthorize(c: Context, parameters: string): Promise<Response> {
  const res = await authlete.authorization.processRequest({
    serviceId: config.authleteServiceId,
    authorizationRequest: { parameters },
  });

  switch (res.action) {
    case "INTERACTION":
    case "NO_INTERACTION": {
      // Both cases redirect to auth-ui. auth-ui inspects its own session to
      // decide whether to skip rendering (prompt=none) or surface login.
      if (!res.ticket) {
        return c.json(
          { error: "server_error", error_description: "Authlete returned INTERACTION without a ticket" },
          500,
        );
      }
      await storeContext(res.ticket, { v: 1, auth: res });
      const url = new URL(config.authUiUrl);
      url.searchParams.set("interaction", res.ticket);
      return c.redirect(url.toString(), 302);
    }
    case "LOCATION":
      return c.redirect(res.responseContent ?? "", 302);
    case "FORM":
      return c.html(res.responseContent ?? "");
    case "BAD_REQUEST":
      return c.body(res.responseContent ?? "{}", 400, jsonHeaders);
    case "INTERNAL_SERVER_ERROR":
    default:
      return c.body(res.responseContent ?? "{}", 500, jsonHeaders);
  }
}

authorize.get("/oauth/authorize", async (c) => {
  const search = new URL(c.req.url).search;
  const parameters = search.startsWith("?") ? search.slice(1) : search;
  return handleAuthorize(c, parameters);
});

authorize.post("/oauth/authorize", async (c) => {
  const parameters = await c.req.text();
  return handleAuthorize(c, parameters);
});

authorize.get("/oauth/authorize/finalize", async (c) => {
  const ticket = c.req.query("ticket");
  if (!ticket) {
    return c.json({ error: "invalid_request", error_description: "missing ticket" }, 400);
  }

  const ctx = await loadContext(ticket);
  if (!ctx) {
    return c.json({ error: "invalid_request", error_description: "ticket not found or expired" }, 400);
  }
  if (!ctx.decision) {
    return c.json(
      { error: "invalid_request", error_description: "no decision recorded for this ticket" },
      400,
    );
  }

  if (ctx.decision.outcome === "denied") {
    const res = await authlete.authorization.fail({
      serviceId: config.authleteServiceId,
      authorizationFailRequest: {
        ticket,
        reason: mapDenyReason(ctx.decision.error),
      },
    });
    return dispatchFinalAction(c, res.action, res.responseContent);
  }

  const res = await authlete.authorization.issue({
    serviceId: config.authleteServiceId,
    authorizationIssueRequest: {
      ticket,
      subject: ctx.decision.subject,
      authTime: ctx.decision.authenticatedAt,
      acr: ctx.decision.acr,
      claims: ctx.decision.userClaims ? JSON.stringify(ctx.decision.userClaims) : undefined,
      scopes: ctx.decision.grantedScopes,
    },
  });
  return dispatchFinalAction(c, res.action, res.responseContent);
});

function dispatchFinalAction(c: Context, action: string | undefined, responseContent: string | undefined): Response {
  switch (action) {
    case "LOCATION":
      return c.redirect(responseContent ?? "", 302);
    case "FORM":
      return c.html(responseContent ?? "");
    case "BAD_REQUEST":
      return c.body(responseContent ?? "{}", 400, jsonHeaders);
    case "INTERNAL_SERVER_ERROR":
    default:
      return c.body(responseContent ?? "{}", 500, jsonHeaders);
  }
}

function mapDenyReason(error: string): "DENIED" | "NOT_LOGGED_IN" | "CONSENT_REQUIRED" | "UNKNOWN" {
  switch (error) {
    case "access_denied":
      return "DENIED";
    case "login_required":
      return "NOT_LOGGED_IN";
    case "consent_required":
      return "CONSENT_REQUIRED";
    default:
      return "UNKNOWN";
  }
}
